name: build-site
run-name: build live site

on:
  workflow_call:
  workflow_dispatch:

env:
  PREVIEWS_FOLDER: preview

permissions:
  contents: write

jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Ruby 3.0.7
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0.7"
          bundler-cache: false  # Disable caching to avoid stale gems

      - name: Upgrade RubyGems to latest (>= 3.4)
        run: gem update --system 3.4.22

      - name: Show RubyGems version (debug)
        run: gem -v

      - name: Install dependencies
        run: bundle install --jobs 4
